name: Lint Project

on:
  push:
    branches: ["**"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: docker.io/golangci/golangci-lint:latest
    steps:
      - uses: actions/checkout@v3
      - run: golangci-lint run

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false